### ISSUE TITLE
Error opening results file

### ISSUE THREAD

**Issue by reedacartwright** [reedacartwright/spagedi#1]
On Linux, the program throws an error when trying to open an output file:

'WARNING: Cannot open results file ".".'

Below is the full log:

<pre>
DATA / RESULTS FILE NAMES

Enter the name of the data file (with ext)
  or press RETURN for the default data file "in.txt"
  or enter a SPACE for importing a data file from FSTAT or GENEPOP format

  Data file: data.txt

  Data file: data.txt
    full path: data.txt

Enter the name of the results file (with ext)
or press RETURN for the default results file "out.txt"

  Results file: out.txt

  Results file: out.txt
    full path: ./out.txt

WARNING: Cannot open results file ".".
If it is being used by another application, close it first. Then press RETURN.
Press ctrl+c if you wish to stop the program now.
</pre>

**Comment by amesclir** [comment]
I have download the last version of Spagedi for Linux, and I am having the same problem. Is there anyway to fix this?
